name       : mate-panel
version    : 1.22.2
release    : 23
source     :
    - https://github.com/mate-desktop/mate-panel/archive/v1.22.2.tar.gz : 87b9273e0caac36476f24069ae71f17b9f081edaab1a8613a719e5c7503879be
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
summary    : The panel of the MATE Desktop
description: |
    The panel of the MATE Desktop Environment
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmate-menu)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mateweather)
    - pkgconfig(sm)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --disable-static \
        --disable-maintainer-mode \
        --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
