name       : mate-panel
version    : 1.20.3
release    : 16
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-panel-1.20.3.tar.xz : ceb56d7de37c162e3671e3bf061753d0af3aa3b8e477b04ddb90301a9ab6e856
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
summary    : The panel of the MATE Desktop
description: |
    The panel of the MATE Desktop Environment
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(ice)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmate-menu)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mateweather)
    - pkgconfig(sm)
    - pkgconfig(xau)
    - pkgconfig(xrandr)
    - itstool
setup      : |
    %configure --disable-static \
               --with-gtk-doc-html
build      : |
    %make
install    : |
    %make_install
