name       : mate-panel
version    : 1.20.0
release    : 12
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-panel-1.20.0.tar.xz : a7326a679ce5b472dcc9fe45988da2cf33e9538b6c20c541633257bdb9bbe133
license    :
    - GPL-2.0
    - LGPL-2.0
    - GFDL-1.1
component  : desktop.mate
summary    : The panel of the MATE Desktop
description: |
    The panel of the MATE Desktop Environment
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(ice)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmate-menu)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mateweather)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - pkgconfig(xau)
    - pkgconfig(xrandr)
    - itstool
setup      : |
    %configure --disable-static \
               --with-gtk-doc-html
build      : |
    %make
install    : |
    %make_install
