name       : mate-panel
version    : 1.18.0
release    : 4
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-panel-1.18.0.tar.xz : 95c12bb7224b4bcf01dccaa863f31dc1bf2c4b1029e5cace92d786ee12133bae
license    :
    - GPL-2.0
    - LGPL-2.0
    - GFDL-1.1
component  : desktop.mate
summary    : The panel of the MATE Desktop
description: |
    The panel of the MATE Desktop Environment
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmate-menu)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mateweather)
    - pkgconfig(xau)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - itstool
setup      : |
    %configure --disable-static --with-gtk=3.0 --with-x
build      : |
    %make
install    : |
    %make_install
