name       : mate-panel
version    : 1.16.0
release    : 3
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-panel-1.16.0.tar.xz : 085b4236f793556381769aeb11744abdebff37254b2ab3eb9f57008d9f93094a
license    :
    - GPL-2.0
    - LGPL-2.0
    - GFDL-1.1
component  : desktop.mate
summary    : The panel of the MATE Desktop
description: |
    The panel of the MATE Desktop Environment
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmate-menu)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mateweather)
    - pkgconfig(xau)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - itstool
setup      : |
    %configure --disable-static --with-gtk=3.0 --with-x
build      : |
    %make
install    : |
    %make_install
