name       : mate-panel
version    : 1.26.1
release    : 32
source     :
    - https://github.com/mate-desktop/mate-panel/releases/download/v1.26.1/mate-panel-1.26.1.tar.xz : 683038c483456e5068f5bb20c3d565936700c9898005c7149ee7aa44e5cc110d
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
summary    : The panel of the MATE Desktop
description: |
    The panel of the MATE Desktop Environment
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmate-menu)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mateweather)
    - pkgconfig(sm)
    - itstool
setup      : |
    %configure --disable-static \
        --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
